from enum import Enum

class Contribution(Enum):
    Chair="Chair"
    ContactPerson="ContactPerson"
    DataCollector="DataCollector"
    DataCurator="DataCurator"
    DataManager="DataManager"
    Distributor="Distributor"
    Editor="Editor"
    HostingInstitution="HostingInstitution"
    Producer="Producer"
    ProjectLeader="ProjectLeader"
    ProjectManager="ProjectManager"
    ProjectMember="ProjectMember"
    RegistrationAgency="RegistrationAgency"
    RegistrationAuthority="RegistrationAuthority"
    RelatedPerson="RelatedPerson"
    Researcher="Researcher"
    ResearchGroup="ResearchGroup"
    Reviewer="Reviewer"
    ReviewerExternal="review-external"
    ReviewAssistant="review-assistant"
    RightsHolder="RightsHolder"
    Sponsor="Sponsor"
    StatsViewer="stats-reviewer"
    Supervisor="Supervisor"
    Translator="Translator"
    WorkPackageLeader="WorkPackageLeader"
    Other="Other"
